spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Phamtrongtin1234
        url: jdbc:mysql://localhost:3306/hightee_queen_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    messages:
        basename: i18n/messages
        encoding: UTF-8
        default-locale: en
api:
    prefix: api/v1
jwt:
    expiration: 2592000
    secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging.level.org.springframework.security: DEBUG

